import smtplib
from email.mime.text import MIMEText
from email.mime.multipart import MIMEMultipart
import json
import os
from pathlib import Path

# Paths
SETTINGS_FILE = Path(__file__).parent / "data" / "settings.json"

def load_settings():
    if SETTINGS_FILE.exists():
        try:
            with open(SETTINGS_FILE, "r") as f:
                return json.load(f)
        except:
            return {}
    return {}

def send_email(to_email: str, subject: str, html_content: str):
    settings = load_settings()
    smtp_server = settings.get("smtp_server")
    smtp_port = settings.get("smtp_port")
    smtp_user = settings.get("smtp_user")
    smtp_password = settings.get("smtp_password")
    
    if not all([smtp_server, smtp_port, smtp_user, smtp_password]):
        print("ERROR: Missing SMTP settings. Cannot send email.")
        return False

    try:
        msg = MIMEMultipart()
        msg['From'] = smtp_user
        msg['To'] = to_email
        msg['Subject'] = subject
        msg.attach(MIMEText(html_content, 'html'))

        server = smtplib.SMTP(smtp_server, int(smtp_port))
        server.starttls()
        server.login(smtp_user, smtp_password)
        text = msg.as_string()
        server.sendmail(smtp_user, to_email, text)
        server.quit()
        print(f"Email sent successfully to {to_email}")
        return True
    except Exception as e:
        print(f"Failed to send email: {e}")
        return False

def format_deal_email(scan_results, query):
    """
    Formats a list of deals into an HTML email body.
    """
    html = f"""
    <html>
    <head>
        <style>
            body {{ font-family: Arial, sans-serif; }}
            .deal-card {{ border: 1px solid #ddd; padding: 10px; margin-bottom: 10px; border-radius: 5px; }}
            .deal-title {{ font-size: 16px; font-weight: bold; color: #333; }}
            .deal-price {{ color: #2ecc71; font-weight: bold; }}
            .deal-meta {{ color: #777; font-size: 12px; }}
            .btn {{ display: inline-block; padding: 5px 10px; background-color: #007bff; color: white; text-decoration: none; border-radius: 3px; font-size: 12px; }}
        </style>
    </head>
    <body>
        <h2>Marketplace Hunter Report: {query}</h2>
        <p>Here are the top deals found in the latest scan:</p>
    """
    
    if not scan_results or len(scan_results) == 0:
        html += "<p>No significant deals found this time.</p>"
    else:
        for deal in scan_results[:10]: # Top 10
            image_html = ""
            if deal.get("image_url"):
                 # Note: Local images won't show in email unless hosted. 
                 # We'll use the alt text or a placeholder if it's local.
                 # ideally we would upload or attach, but for now we skip invalid img
                 pass
            
            html += f"""
            <div class="deal-card">
                <div class="deal-title">{deal.get('title', 'Unknown Item')}</div>
                <div class="deal-price">{deal.get('price', 'N/A')}</div>
                <div class="deal-meta">{deal.get('location', 'Unknown Location')}</div>
                <p>{deal.get('ai_analysis', {}).get('reason', 'No analysis available.')}</p>
                <a href="{deal.get('url', '#')}" class="btn">View on Facebook</a>
            </div>
            """
            
    html += """
        <p><small>Generated by Marketplace Hunter AI</small></p>
    </body>
    </html>
    """
    return html
